# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [10]:
import numpy as np

#### Create an array of 10 zeros

In [11]:
a=np.array([0,0,0,0,0,0,0,0,0,0])
print(a)



[0 0 0 0 0 0 0 0 0 0]


#### Create an array of 10 ones

In [12]:
a=np.array([1,1,1,1,1,1,1,1,1,1])
print(a)

[1 1 1 1 1 1 1 1 1 1]


#### Create an array of 10 fives

In [ ]:
a=np.array([5,5,5,5,5,5,5,5,5,5])
print(a)

[5 5 5 5 5 5 5 5 5 5]


#### Create an array of the integers from 10 to 50

In [13]:
x=np.arange(10,50)
print("array from 10 to 50 :")
print(x)

array from 10 to 50 :
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### Create an array of all the even integers from 10 to 50

In [14]:
x=np.arange(10,50,2)
print("array of all the even integers from 10 t0 50:")
print(x)


array of all the even integers from 10 t0 50:
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [19]:
x= np.arange(9).reshape(3, 3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Create a 3x3 identity matrix

In [27]:
array=np.eye(3)

print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1

In [31]:
rand_num=np.random.normal(0,1,1)
print(rand_num)

[-1.58574986]


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [34]:
rand_num=np.random.normal(0,1,25)
print(rand_num)

[-0.92200199  0.51285466 -0.69063895  1.34006004 -0.6380015   1.54226003
 -0.4332326  -1.37597308 -0.41198327  0.21417209  0.30660241  1.22932762
  1.37994732 -0.93141983 -1.694703    1.97121389  1.47248084 -1.42222301
 -0.04324709  0.9996703   0.54383138  0.03963664  0.81657213  0.43381367
 -2.77090224]


#### Create the following matrix:

#### Create an array of 20 linearly spaced points between 0 and 1:

In [41]:
array=np.linspace(0,1,20)
print(array)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
mat[2: ,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [49]:
mat[3,4]


TypeError: list indices must be integers or slices, not tuple

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
mat[4]

array([21, 22, 23, 24, 25])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [ ]:
mat.sum()

325

#### Get the standard deviation of the values in mat

In [ ]:
mat.std()

7.2111025509279782

#### Get the sum of all the columns in mat

In [ ]:
mat.sum(axis=1)

array([55, 60, 65, 70, 75])

# Great Job!